server:
  port: 8085

spring:
  application:
    name: media-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: agriconnect-media
  public-url: http://localhost:9000