server:
  port: 8083

spring:
  application:
    name: farm-management-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: agriconnect_farm
      username: agriconnect
      password: agriconnect123
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: farm-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.agriconnect.*"